# Generated by Django 4.2.3 on 2023-12-22 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0006_contact_alter_aboutme_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slider",
            options={},
        ),
    ]
